# -*- coding: utf-8 -*-
"""TechChallenge5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NJVbAHC4A7Fw04pvF1YpSk1_VZGzT8qk
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

plt.ion()

arquivo = "pede.xlsx"

indicadores = [
    "IAN","IDA","IEG","IAA","IPS","IPP","IPV","INDE"
]

def limpar_numero(x):
    if pd.isna(x):
        return np.nan
    x = str(x).strip().replace(",", ".")
    try:
        return float(x)
    except:
        return np.nan

def encontrar_coluna(dataset, palavras):
    for palavra in palavras:
        for col in dataset.columns:
            if palavra in col:
                return col
    return None



print("\nCarregando arquivo...")
sheets = pd.read_excel(arquivo, sheet_name=None)
dfs = []

for nome, df in sheets.items():
    nome_limpo = nome.strip().upper()

    if "2022" in nome_limpo:
        df["ANO"] = 2022
    elif "2023" in nome_limpo:
        df["ANO"] = 2023
    elif "2024" in nome_limpo:
        df["ANO"] = 2024
    else:
        df["ANO"] = np.nan

    dfs.append(df)

dataset = pd.concat(dfs, ignore_index=True)
dataset.columns = dataset.columns.str.strip().str.upper()
dataset = dataset.loc[:, ~dataset.columns.duplicated()]

print("\nValores únicos de ANO:")
print(dataset["ANO"].unique())


dataset.replace(["", " ", "NA", "NAN"], np.nan, inplace=True)
dataset.drop_duplicates(inplace=True)


col_mat = encontrar_coluna(dataset, ["MAT"])
col_port = encontrar_coluna(dataset, ["PORT"])
col_ing = encontrar_coluna(dataset, ["ING"])

col_ieg = encontrar_coluna(dataset, ["IEG"])
col_iaa = encontrar_coluna(dataset, ["IAA"])
col_ips = encontrar_coluna(dataset, ["IPS"])
col_ipv = encontrar_coluna(dataset, ["IPV"])
col_inde = encontrar_coluna(dataset, ["INDE"])

col_defas = encontrar_coluna(dataset, ["DEFAS"])


def calcular_ian(defas):
    if pd.isna(defas):
        return np.nan
    if defas >= 0:
        return 10
    elif defas == -1:
        return 7.5
    elif defas == -2:
        return 5
    else:
        return 2.5

if col_defas:
    dataset[col_defas] = dataset[col_defas].apply(limpar_numero)

    dataset["IAN_CALCULADO"] = dataset[col_defas].apply(calcular_ian)

    if "IAN" in dataset.columns:
        dataset["IAN"] = dataset["IAN"].combine_first(dataset["IAN_CALCULADO"])
    else:
        dataset["IAN"] = dataset["IAN_CALCULADO"]


if col_mat and col_port and col_ing:
    dataset["IDA"] = dataset[[col_mat, col_port, col_ing]].applymap(limpar_numero).mean(axis=1)


if col_ieg:
    dataset["IEG"] = dataset[col_ieg].apply(limpar_numero)
if col_iaa:
    dataset["IAA"] = dataset[col_iaa].apply(limpar_numero)
if col_ips:
    dataset["IPS"] = dataset[col_ips].apply(limpar_numero)
if col_ipv:
    dataset["IPV"] = dataset[col_ipv].apply(limpar_numero)
if col_inde:
    dataset["INDE"] = dataset[col_inde].apply(limpar_numero)



def converter_avaliacao(x):
    if pd.isna(x):
        return np.nan

    x = str(x).strip().upper()

    if "BOLSA" in x:
        return 10
    elif "PROMOVIDO" in x:
        return 8
    elif "MANTIDO" in x:
        return 5
    elif "REQUER" in x:
        return 2
    else:
        return np.nan

cols_av = []

for col in dataset.columns:
    if dataset[col].dtype == object:
        amostra = dataset[col].dropna().astype(str).str.upper()

        if any(amostra.str.contains("PROMOVIDO|MANTIDO|BOLSA|REQUER", na=False)):
            cols_av.append(col)

print("\nColunas de avaliação detectadas:")
for c in cols_av:
    print(c)

print("\nContagem de valores por coluna:")
for col in cols_av:
    print(col, "->", dataset[col].notna().sum())


cols_num = []

for col in cols_av:
    nova_col = col + "_NUM"
    dataset[nova_col] = dataset[col].apply(converter_avaliacao)
    cols_num.append(nova_col)


dataset["IPP"] = dataset[cols_num].mean(axis=1, skipna=True)

print("\nIPP por ano:")
print(dataset.groupby("ANO")["IPP"].count())



for col in indicadores:
    if col in dataset.columns:

        print(f"\nContagem de valores válidos para {col}:")
        print(dataset.groupby("ANO")[col].count())

        temp = dataset[["ANO", col]].dropna()

        if len(temp) == 0:
            continue

        medias = temp.groupby("ANO")[col].mean().sort_index()
        medias.index = medias.index.astype(int)

        plt.figure(figsize=(8,5))
        plt.plot(medias.index, medias.values, marker="o")

        plt.xticks(medias.index)

        for x, y in zip(medias.index, medias.values):
            plt.text(x, y, f"{y:.2f}", ha='center')

        plt.title(f"Evolução média do {col} por Ano")
        plt.xlabel("Ano")
        plt.ylabel(col)
        plt.grid()
        plt.tight_layout()
        plt.show()


cols_corr = [c for c in indicadores if c in dataset.columns]
corr = dataset[cols_corr].corr()

print("\nCorrelação:")
print(corr)

plt.figure(figsize=(7,6))
plt.imshow(corr, vmin=-1, vmax=1)
plt.colorbar()
plt.xticks(range(len(cols_corr)), cols_corr, rotation=45)
plt.yticks(range(len(cols_corr)), cols_corr)
plt.title("Mapa de correlação")
plt.tight_layout()
plt.show()

print("\nANÁLISE FINALIZADA")

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.ensemble import RandomForestClassifier

import joblib

plt.ion()


arquivo = "pede.xlsx"

sheets = pd.read_excel(arquivo, sheet_name=None)

dfs = []

for nome_aba, df in sheets.items():

    ano = ''.join(filter(str.isdigit, nome_aba))

    if ano != "":
        df["ANO"] = int(ano)

    dfs.append(df)

dataset = pd.concat(dfs, ignore_index=True)


dataset.columns = dataset.columns.str.strip().str.upper()

dataset.replace(["", " ", "NA", "NAN"], np.nan, inplace=True)

dataset.drop_duplicates(inplace=True)

print("\nCOLUNAS DO DATASET:")
print(dataset.columns)


indicadores = ["IAN","IDA","IEG","IAA","IPS","IPP","IPV","INDE"]

for col in indicadores:

    if col in dataset.columns:

        dataset[col] = pd.to_numeric(dataset[col], errors="coerce")


defasagem_col = None

for col in dataset.columns:

    if "DEFASAGEM" in col:

        defasagem_col = col
        break

if defasagem_col is None:

    raise ValueError("Nenhuma coluna DEFASAGEM encontrada.")

print("\nColuna de defasagem:", defasagem_col)


dataset["RISCO_DEFASAGEM"] = dataset[defasagem_col].apply(
    lambda x: 1 if pd.notna(x) and x < 0 else 0
)

print("\nDistribuição do risco:")

print(dataset["RISCO_DEFASAGEM"].value_counts())


indicadores_ml = ["IAN","IDA","IEG","IAA","IPS","IPP","IPV"]

features = [c for c in indicadores_ml if c in dataset.columns]

print("\nIndicadores utilizados:")

print(features)

X = dataset[features]

y = dataset["RISCO_DEFASAGEM"]


X_train, X_test, y_train, y_test = train_test_split(

    X,
    y,
    test_size=0.30,
    random_state=42
)


pipeline = Pipeline([

    ("imputer", SimpleImputer(strategy="mean")),

    ("model", RandomForestClassifier(

        n_estimators=200,
        random_state=42
    ))
])


pipeline.fit(X_train, y_train)


y_pred = pipeline.predict(X_test)

print("\n===== MATRIZ DE CONFUSÃO =====")

print(confusion_matrix(y_test, y_pred))

print("\n===== RELATÓRIO DE CLASSIFICAÇÃO =====")

print(classification_report(y_test, y_pred))


modelo = pipeline.named_steps["model"]

importancia = pd.Series(

    modelo.feature_importances_,
    index=features

).sort_values(ascending=False)

print("\n===== IMPORTÂNCIA DOS INDICADORES =====")

print(importancia)

plt.figure()

importancia.plot(kind="bar")

plt.title("Importância dos Indicadores para Prever Risco")

plt.ylabel("Importância")

plt.show()


probabilidades = pipeline.predict_proba(X)[:,1]

dataset["PROB_RISCO_DEFASAGEM"] = probabilidades

print("\nExemplo de probabilidades:")

print(dataset[["PROB_RISCO_DEFASAGEM"] + features].head())


plt.figure()

plt.hist(dataset["PROB_RISCO_DEFASAGEM"], bins=20)

plt.title("Distribuição da Probabilidade de Risco")

plt.xlabel("Probabilidade")

plt.ylabel("Número de alunos")

plt.show()


joblib.dump(pipeline, "modelo_risco_defasagem.pkl")

print("\nPipeline salvo como modelo_risco_defasagem.pkl")


pipeline_carregado = joblib.load("modelo_risco_defasagem.pkl")

print("\nPipeline carregado com sucesso!")


exemplo = X.iloc[:5]

prob_prevista = pipeline_carregado.predict_proba(exemplo)[:,1]

print("\nProbabilidade prevista para primeiros alunos:")

print(prob_prevista)